/* K1 Shooters club app — the four pillars, each taught through a team the boys can watch.
 *
 * The academy development model already names our identity: Barcelona’s brain, Arsenal’s
 * swagger, Man City’s structure, and Kasi fire. These masterclasses turn each pillar from a
 * line on a poster into football a boy can see, copy and be corrected on. Real Madrid is added
 * at the end on purpose — not as a pillar, but as the honest reminder that our four teachers
 * do not all agree with each other. */
(function (K1) {
  'use strict';
  const R = mc => K1.Masterclass.register(mc);
  const GROUP = 'The four pillars';

  /* ==================================================== BARCELONA’S BRAIN */
  R({
    id: 'pillar-brain', group: GROUP, title: 'Barcelona’s Brain',
    subtitle: 'Pillar one · knowing where to stand before the ball arrives', coach: 'Barcelona',
    level: 'U11 and up', duration: '25 min', accent: '#a50044',
    summary: 'Our model puts Barcelona’s brain first for a reason. Brain does not mean tricks and it does not mean slow. It means that by the time the ball reaches you, the hard thinking is already finished — because you did it while the ball was still somewhere else.',
    sessionIds: ['k1_rondo_5v2', 'rondo_4v2', 'k1_buildup_6v5'],
    slides: [
      { kind: 'chapter', title: 'Barcelona’s Brain', lead: 'Game intelligence, positional play, decisions.' },
      { title: 'Brain is not the same as talent', lead: 'A boy with a brain is not the one who does the most with the ball. He is the one who has to do the least.',
        points: [
          'The clever player receives the ball already facing the way he wants to go.',
          'He does that because he looked over his shoulder twice before it came.',
          'What looks like a brilliant first touch is usually just early information.',
          'This is the one part of football that costs nothing and needs no gym.',
        ],
        quote: { text: 'Field vision, or the ability to accurately predict and see potential passes, has become the cornerstone of modern football tactics.', by: 'James Wilcox and Gus Ellison', source: 'In Sight, 2021' },
        say: { script: 'Some of you are waiting to be told you are talented. I am telling you the fastest way to look talented on Saturday is to turn your head on Tuesday.',
          ask: 'When last did you look over your shoulder before the ball came to you? Be honest.',
          cue: 'Two looks before it arrives.' },
        note: 'Note the two words in that quote: predict and see. Scanning is not just looking, it is guessing what is about to be on. This is the cheapest improvement available to a township academy — no equipment, no budget, only insistence.' },
      { title: 'Five lanes, and nobody stands in a friend’s lane', lead: 'Positional play in one sentence: the pitch is cut into five lanes — the five vertical corridors — and we spread across them so their defenders cannot cover two of us at once.',
        points: [
          'Two of us in the same lane means one defender marks both. We have wasted a player.',
          'When we are spread properly, every pass forward has a team-mate at the end of it.',
          'Width is not for the winger’s benefit. It is to stretch their back line so the middle opens.',
          'The full-back or the winger holds the touchline — one of them, never both, never neither.',
        ],
        board: { formation: '235', away: '442low', pitch: 'full', overlay: 'laneslab' },
        caption: '2-3-5 · five men, five corridors, nobody doubled up.',
        say: { script: 'Look at the names on the side of that picture. Wide, half-space, centre. Those five words are going to follow you until you leave this club.',
          ask: 'Two of you are standing in the same lane. Which one of you is going to move, and where to?',
          cue: 'Check your lane.' },
        coaching: ['Freeze the game and ask who is doubled up', 'Make the boys name their lane out loud', 'A winger who comes inside must send the full-back outside — the lane is never left empty'] },
      { title: 'The rondo is not a warm-up', lead: 'It is the lesson. Everything else is a bigger version of it.',
        points: [
          'In a rondo you learn to receive side-on, to find the free man, and to press for five seconds when you lose it.',
          'That is build-up, progression and counter-press, all inside a ten-metre square.',
          'If the boys treat it as a game before training, you have wasted the best coaching tool you own.',
          'Keep score. Count passes. Make losing the ball cost something.',
        ],
        board: { drill: 'k1_rondo_5v2' },
        caption: 'Our own 5v2 — the K1 version.',
        say: { script: 'This little square is not to warm you up. Everything I am going to shout at you on Saturday, you will have already practised in here.',
          ask: 'You are in the middle and you cannot win it. What did the passer do to make you look silly?',
          cue: 'Side-on. Head up. Free man.' } },
      { title: 'The free man', lead: 'Their press has a mathematical problem: if they send an extra man at the ball, somebody of ours is unmarked. Our job is to find him before they fix it.',
        points: [
          'The free man is almost never the one shouting for it.',
          'He is usually behind the presser, or on the far side of the pitch.',
          'The pass to him is often backwards first. Backwards is not negative if it finds the free man.',
          'Once he receives with his head up, we have broken a line without a tackle.',
        ],
        board: { phase: 'ph_build_gk' },
        caption: 'Goalkeeper included — he is the reason we have a spare man.',
        quote: { text: 'Playing football is very simple, but playing simple football is the hardest thing there is.', by: 'Johan Cruyff' },
        say: { script: 'Their press only works if they have as many men as we do. The second they send one extra, they have given us a free man somewhere. Find him.',
          ask: 'Their striker just left the centre-back to press the keeper. Who is free now, and who is going to see him?',
          cue: 'Where is the free man?' } },
      { title: 'What we take from Barcelona', lead: 'Not their players and not their budget.',
        points: [
          'Scan before you receive. Two looks, every time.',
          'Know your lane and do not stand in a team-mate’s.',
          'Find the free man, even if the pass goes backwards to reach him.',
          'Treat the rondo as the lesson, not the warm-up.',
        ],
        say: { script: 'Four things. None of them need money, boots or height. That is why this pillar is first in our model.',
          cue: 'Look first. Then play.' } },
    ],
    sources: [
      'K1 Shooters Academy Youth Development Model (club document) — “Barcelona’s brain”.',
      'James Wilcox and Gus Ellison, “In Sight: The Modern Tactics Behind a Footballer’s Field of View” (2021) — field vision, the five vertical corridors.',
    ],
  });

  /* ====================================================== ARSENAL’S SWAGGER */
  R({
    id: 'pillar-swagger', group: GROUP, title: 'Arsenal’s Swagger',
    subtitle: 'Pillar two · flair with a structure underneath it', coach: 'Arsenal',
    level: 'U13 and up', duration: '25 min', accent: '#ef0107',
    summary: 'Swagger is the pillar most likely to be misunderstood, by boys and by coaches. It is not showboating and it is not selfishness. It is the confidence to take a man on at the moment the team has built for you — and the discipline to know when that moment is not now.',
    sessionIds: ['one_v_one', 'k1_waves_1v1_2v1', 'crossing_finishing_fullpitch'],
    slides: [
      { kind: 'chapter', title: 'Arsenal’s Swagger', lead: 'Creative expression, flair, confidence on the ball.' },
      { title: 'Swagger is permission, not permission to be selfish', lead: 'Every academy in the world says it wants brave players. Most of them shout at the first boy who tries something and loses it.',
        points: [
          'If we punish the failed dribble in our own half, we will never see the successful one in theirs.',
          'So we make it a rule, not a mood: in the final third, take him on. In our own third, play simple.',
          'A boy needs to know exactly where the licence starts. Draw the line on the board and never move it.',
          'Then when he does try it and it fails, nobody on the touchline is allowed to groan. Including us.',
        ],
        board: { formation: '433', away: '442low', pitch: 'full', overlay: 'zones15' },
        caption: 'The line is the last third. Behind it, simple. Inside it, go.',
        say: { script: 'I am giving you permission, but it has a line on it. Look at the board. Inside that last third, if you are one against one, go. Behind it, give me the simple pass.',
          ask: 'You are our left-back, in our own half, and you fancy the nutmeg. What are you going to do instead?',
          cue: 'Simple behind, brave in front.' },
        note: 'Our model calls this creative expression and puts it second on purpose. It comes after the brain, not instead of it.' },
      { title: 'The structure that pays for the flair', lead: 'Arsenal’s wingers get those one-against-ones because ten other things happened first.',
        points: [
          'The left-back steps inside, so the team has an extra man in midfield and can keep the ball.',
          'Five players hold the last line, so their defence cannot slide across.',
          'The team overloads one side until the opposition leans that way.',
          'Then the ball is switched — and the far winger is alone with his man and grass in front of him.',
        ],
        board: { morph: 'arsenal_433_325' },
        caption: 'Play all four frames: base · overload · switch · counter-press.',
        say: { script: 'Watch this animation twice. The first time watch the ball. The second time watch the winger on the far side, who is doing nothing at all for ten seconds and then gets the best moment of the match.',
          ask: 'Why is he so free? What did the other ten do to make that happen?',
          cue: 'Overload one side to free the other.' },
        coaching: ['Nobody is “not involved” — the far winger is working by staying wide', 'The switch must be one pass or two, not five', 'The moment the ball arrives on the far side, the 1v1 licence is on'] },
      { title: 'Overload to isolate', lead: 'The oldest trick in possession football, and the most useful thing we can teach a winger who wants to dribble.',
        points: [
          'Pull four or five of our players to one side of the pitch.',
          'Their defence shifts across, because it has to.',
          'The far winger stays exactly where he is. He does not come and join in.',
          'Switch the ball. Now it is him against one defender, with nobody nearby to help.',
        ],
        board: { formation: '325', away: '442low', pitch: 'full', overlay: 'laneslab', ball: [62, 58] },
        caption: 'The switch has landed. One defender, one winger, grass.',
        say: { script: 'The hardest instruction I will ever give a winger is: stand still and stay wide while the ball is on the other side. It feels like you are doing nothing. You are doing the most important thing on the pitch.',
          ask: 'The ball is on the left. You are our right winger. Where exactly do you stand, and why not closer?',
          cue: 'Stay wide. Wait for it.' } },
      { title: 'The 1v1, coached properly', lead: 'Confidence is not a speech. It is repetitions in a situation the boy recognises.',
        points: [
          'Give every attacker the same start: ball at his feet, defender in front, space behind.',
          'Do not correct the trick. Correct the setup — attack the defender’s front foot, change speed, finish.',
          'Twenty repetitions a week beats one talk about belief.',
          'Keep a count of successful take-ons in matches and read it out. What we measure, they value.',
        ],
        board: { drill: 'one_v_one' },
        say: { script: 'I am not going to teach you a skill move. Choose your own. I am going to teach you when to use it and how to set the defender up first.',
          ask: 'Which foot is the defender leaning on? Go past that side.',
          cue: 'Change of speed, not just feet.' } },
      { title: 'What we take from Arsenal', lead: 'Kasi boys already have swagger. This pillar is about protecting it, not creating it.',
        points: [
          'Draw the line: simple behind it, brave in front of it.',
          'Never groan at a failed take-on inside the final third.',
          'Overload one side to isolate the other.',
          'Wingers hold their width even when the ball is nowhere near them.',
        ],
        say: { script: 'Of the four pillars, this is the one you already brought with you. My job is not to give it to you. My job is to make sure the structure does not kill it.',
          cue: 'Brave in the right place.' } },
    ],
    sources: [
      'K1 Shooters Academy Youth Development Model (club document) — “Arsenal’s swagger”.',
      'Overload-to-isolate and the inverted full-back as described in public tactical analysis of Arsenal under Mikel Arteta.',
    ],
  });

  /* ===================================================== MAN CITY’S STRUCTURE */
  R({
    id: 'pillar-structure', group: GROUP, title: 'Man City’s Structure',
    subtitle: 'Pillar three · the shape that makes everything else repeatable', coach: 'Manchester City',
    level: 'U13 and up', duration: '30 min', accent: '#6cabdd',
    summary: 'Structure is the least exciting pillar and the one that wins leagues. It is the promise that every boy knows where he stands, where his team-mates are, and what happens the second the ball is lost — so that the brain and the swagger have somewhere safe to operate.',
    sessionIds: ['k1_pattern_fb_pivot', 'k1_zone_buildup', 'dz_counterpress_zones'],
    slides: [
      { kind: 'chapter', title: 'Man City’s Structure', lead: 'Tactical discipline, build-up precision, collective pressing.' },
      { title: 'Why structure comes before freedom', lead: 'A team without a shape has to solve every situation from scratch. A team with a shape only has to solve the new part.',
        points: [
          'Structure is not a cage. It is a starting grid.',
          'It tells you where to be when you have no better idea — and most of the time you will not have one.',
          'It also tells the other ten where you are, which is how a pass gets played to a space before anybody is standing in it.',
          'The better the structure, the less shouting a coach has to do.',
        ],
        board: { morph: 'city_3241_325' },
        caption: 'Build · attack · recover. The same three pictures, every week.',
        say: { script: 'Some of you think a system is there to stop you playing. It is the opposite. The system is what lets your team-mate pass into a space before you have even got there, because he knows you are coming.',
          ask: 'If I stopped this match right now, could you tell me where our right-back is without looking?',
          cue: 'Same shape, every time.' } },
      { title: 'The full-back who comes inside', lead: 'The single idea that changed modern build-up, and it works at U13 as well as it works in the Premier League.',
        points: [
          'One full-back stops hugging the touchline and steps into midfield beside the anchor.',
          'Now we have three at the back to build and two in front of them to receive — a box.',
          'The winger on that side holds the width instead, so we have not lost the touchline.',
          'And when we lose the ball, the full-back is already central, which is exactly where counter-attacks come through.',
        ],
        board: { formation: '3241', away: '433press', pitch: 'full', overlay: 'laneslab' },
        caption: 'The 3-2 box: three build, two receive, five ahead.',
        say: { script: 'Our model says the full-backs and the anchors are the bridge between defence and attack. This is what that sentence looks like when you draw it.',
          ask: 'You are the left-back and you come inside. Who has to go wide, and what happens if he forgets?',
          cue: 'One in, one out.' },
        coaching: ['Only one full-back inverts at a time', 'The anchor slides across to make room — he does not stand still', 'If the winger does not hold width, do not blame the full-back'] },
      { title: 'Rest defence: the reason they can attack so freely', lead: 'The most important players during a City attack are the three or four who are not in it.',
        points: [
          'While we attack, a small group stays behind the ball on purpose. That is the rest defence.',
          'It is usually the two centre-backs and the anchor, sometimes the inverted full-back as well.',
          'Their job is not to defend a shot. It is to stop the counter-attack before it starts.',
          'This is why a team can send five players forward and still not get caught.',
        ],
        board: { phase: 'ph_prog_third' },
        caption: 'Look behind the ball, not in front of it.',
        say: { script: 'When we score I want you to watch the replay of the three men who never got in the picture. They are the reason the goal happened.',
          ask: 'We have five men in their box. How many of ours are behind the ball, and is that enough?',
          cue: 'Who is our rest defence?' } },
      { title: 'The pause', lead: 'The hardest thing to teach a young team: doing nothing on purpose.',
        points: [
          'A boy with the ball and a shape around him does not have to do something immediately.',
          'If he waits, the opponent has to make a decision — and a defender who moves has left a space.',
          'So: settle the ball, look up, and let them commit first.',
          'Speed is for the moment after the pause, not instead of it.',
        ],
        board: { phase: 'ph_build_trap' },
        caption: 'Stand on it. Make him come. Then go.',
        quote: { text: 'They are the master of when to pass to the free man. They don’t pass the ball until the opponent moves.', by: 'Pep Guardiola', source: 'press conference, May 2023' },
        say: { script: 'Panic is the most contagious thing on a football field. The cure is one man who can stand on the ball for two seconds and look calm while everyone screams at him.',
          ask: 'Nobody is pressing you. Why are you rushing?',
          cue: 'Wait for him to move.' } },
      { title: 'What we take from Man City', lead: 'Structure is the pillar that a township academy can win with, because it costs nothing but repetition.',
        points: [
          'Know your starting position in every phase, without being told.',
          'One full-back inside, one winger outside. Never both, never neither.',
          'Always know who is behind the ball while we attack.',
          'Pause before you play. Make them move first.',
        ],
        say: { script: 'We cannot buy players. We can be the best-organised team in this league by December, and that is entirely up to how we train on a Monday night.',
          cue: 'Shape first, then speed.' } },
    ],
    sources: [
      'K1 Shooters Academy Youth Development Model (club document) — “Man City’s structure”.',
      'The inverted full-back, the 3-2 build box and rest defence as described in public tactical analysis of Manchester City under Pep Guardiola.',
    ],
  });

  /* ============================================================== KASI FIRE */
  R({
    id: 'pillar-kasi', group: GROUP, title: 'Kasi Fire',
    subtitle: 'Pillar four · the one we did not import', coach: 'Orlando Pirates',
    level: 'Every age group', duration: '25 min', accent: '#f5b301',
    summary: 'Three of our pillars came from Europe on a television. This one did not. Kasi fire is township grit and ambition, and our model is explicit that we must never lose the street edge. We teach it through Orlando Pirates, because it is the badge most of our boys already wear.',
    sessionIds: ['k1_futsal_31_22', 'k1_waves_1v1_2v1', 'ssg_3v3_gk'],
    slides: [
      { kind: 'chapter', title: 'Kasi Fire', lead: 'Township grit and ambition. We never lose the street edge.' },
      { title: 'Why this pillar exists at all', lead: 'A club can copy Barcelona and end up with boys who play beautifully and lose every physical contest. Our model refuses that trade.',
        points: [
          'The street gave you your first touch, your balance in a crowd, and your refusal to be bullied.',
          'None of that came from a coaching course, and no coaching course should take it away.',
          'Structure without fire is a team that passes sideways and goes home.',
          'Fire without structure is a team that runs itself out by half-time. We want both.',
        ],
        say: { script: 'Some of you learned football on concrete with a plastic ball and no referee. That is not a disadvantage I am trying to coach out of you. It is the fourth pillar of this academy and it is written in our model.',
          ask: 'What did you learn on the street that you have never been taught here?',
          cue: 'Street meets structure.' } },
      { title: 'Orlando Pirates, and why the badge matters', lead: 'We use Pirates because it is the club our boys can actually go and watch, and the one whose story sounds like ours.',
        points: [
          'Founded in Orlando, Soweto — a township club that became one of the biggest names on the continent.',
          'In 1995 they won the African Cup of Champions Clubs, the top club competition in Africa at the time.',
          'They did it as a South African club, in Africa, against the continent’s best.',
          'That is the ambition half of Kasi fire. Grit alone is survival. Grit with ambition goes somewhere.',
        ],
        quote: { text: 'Once a Pirate, always a Pirate.', by: 'Orlando Pirates supporters' },
        say: { script: 'Every one of the other three pillars is a club you will only ever see on a screen. This one has a stadium you can get a taxi to. That is the point of it.',
          ask: 'Who in here supports Pirates? Good. Now tell me one thing about how they play, not about who they beat.',
          cue: 'From Orlando to Africa.' },
        note: 'Check the current Pirates squad and manager before you present this — the club’s identity is stable, the personnel are not.' },
      { title: 'The shape, so it is not only a feeling', lead: 'Kasi fire has to show up as football, or it is just a slogan on a jersey.',
        points: [
          'A 4-2-3-1 base with two holding players — the shape our own model already prefers.',
          'In possession one full-back flies forward and the other tucks in, making a back three and two wing-backs.',
          'That gives width and bodies forward without leaving the middle open.',
          'It is ambitious and it is covered. That is exactly the balance this pillar is asking for.',
        ],
        board: { morph: 'pirates_4231_343' },
        caption: '4-2-3-1 becoming 3-4-3 — brave, but covered.',
        say: { script: 'Watch what happens to the two full-backs. One goes, one stays. That is not caution, that is how you get to be brave without being stupid.',
          ask: 'Both our full-backs want to attack. Which one goes, and who decides?',
          cue: 'One flies, one holds.' } },
      { title: 'Grit is a skill, not a mood', lead: 'You cannot shout a boy into being brave. You can train the specific things brave players do.',
        points: [
          'Win the second ball. Half of township football is decided by who reacts first to a bounce.',
          'Front-foot defending: meet the ball, do not wait for it to arrive at your box.',
          'Get up. The time between being fouled and being back in position is a coachable number.',
          'Finish the run. Most chances are missed by the player who stopped ten metres early.',
        ],
        board: { drill: 'k1_waves_1v1_2v1' },
        say: { script: 'When I say I want fire, I do not mean shouting. I mean four things, and I can count all four of them from the touchline on Saturday.',
          ask: 'The ball bounces loose between you and their number six. Who gets there, and what has to happen in your head first?',
          cue: 'Second ball is ours.' },
        coaching: ['Count second balls won in the match and read the number out', 'Praise the recovery run louder than the goal', 'Never let a boy walk back into shape'] },
      { title: 'What we take from Kasi', lead: 'This is the pillar we protect rather than build.',
        points: [
          'Keep the street touch. Futsal and small spaces, every week.',
          'Second balls, front-foot defending, get up fast, finish the run.',
          'Ambition is part of the pillar. Grit that expects nothing is just endurance.',
          'Never apologise for where the football came from.',
        ],
        say: { script: 'Three of our pillars we borrowed. This one is ours, and it is the reason a team from here can beat a team with better boots.',
          cue: 'Street meets structure.' } },
    ],
    sources: [
      'K1 Shooters Academy Youth Development Model (club document) — “Kasi fire”.',
      'Orlando Pirates FC — Soweto club history; winners of the 1995 African Cup of Champions Clubs.',
    ],
  });

  /* ============================================== REAL MADRID · THE OTHER WAY */
  R({
    id: 'study-madrid', group: GROUP, title: 'Real Madrid · the other way to win',
    subtitle: 'Not a pillar — the argument against the other four', coach: 'Real Madrid',
    level: 'U15 and up', duration: '25 min', accent: '#febe10',
    summary: 'Our four pillars all point the same way: keep the ball, control the game, build patiently. Real Madrid have spent twenty years winning the biggest matches in football by doing something else. A coach who hides that from his players is teaching them a religion, not a sport.',
    sessionIds: ['transition_4v4_2', 'def_shape_shadow', 'finishing_circuit'],
    slides: [
      { kind: 'chapter', title: 'The other way to win', lead: 'Everything above this slide is one answer. Here is a different one.' },
      { title: 'You do not have to have the ball to be the better team', lead: 'Madrid have won European finals with less of the ball than the team they beat. That is not an accident and it is not luck.',
        points: [
          'A compact block invites the opponent forward, which leaves space behind them.',
          'The moment the ball is won, that space is the most valuable thing on the pitch.',
          'Three or four players attack it immediately, at full speed, before the opponent can get back.',
          'The whole plan is: be organised, wait, then be devastating for eight seconds.',
        ],
        board: { morph: 'madrid_442_433' },
        caption: 'Block · win it · go. Watch how few passes it takes.',
        say: { script: 'I have spent four sessions telling you to keep the ball. Now I am going to show you a team that gives it away on purpose and wins more than anybody.',
          ask: 'If they have the ball for eighty minutes and we score twice, who played better?',
          cue: 'Organised, then ruthless.' } },
      { title: 'The counter-attack is a structure too', lead: 'It looks like chaos on television. It is rehearsed.',
        points: [
          'The first pass after winning it goes forward, or it goes nowhere. Hesitate and the moment is gone.',
          'One runner goes straight down the outside — always. He stretches them.',
          'One runs in behind the centre-backs. One arrives late in the middle for the cut-back.',
          'Three runners, three different lines. Everyone knows which one is theirs before the ball is won.',
        ],
        board: { phase: 'ph_counter' },
        caption: 'Three runners, three lines, one decision.',
        say: { script: 'A counter-attack is not “everybody run”. It is three specific runs and they are yours before the whistle. If two of you make the same run, we have wasted the best six seconds of the match.',
          ask: 'We have just won it on the edge of our own box. Which of the three runs is yours?',
          cue: 'First pass forward.' },
        coaching: ['Rehearse the three runs without opposition first', 'The wide runner must go even when the ball will not reach him', 'If the first pass is sideways, stop the drill and restart'] },
      { title: 'So why do we still build from the back?', lead: 'The honest answer, which the boys deserve.',
        points: [
          'Because we are a development academy, not a results team. Building from the back teaches more football per match than kicking it long.',
          'Because the counter-attack needs players who can already receive under pressure. You cannot skip to the exciting part.',
          'Because our own model chose it: build from the back, exploit the space between the lines, attack in waves.',
          'And because the two are not enemies — a team that can build is also a team that can counter. A team that can only counter is stuck.',
        ],
        board: { formation: '442low', away: '235', pitch: 'full', overlay: 'zones15' },
        caption: 'A low block is a tool. It is not our identity.',
        say: { script: 'We build from the back because it is the harder skill and you are young enough to learn it. When you are twenty-five you can choose to sit in a block. You cannot choose to have a first touch you never developed.',
          ask: 'When would a low block actually be the right plan for us?',
          cue: 'Learn the hard one first.' } },
      { title: 'Our teachers disagree, and that is the lesson', lead: 'Four pillars and one dissenter. Hold all five and you are a coach, not a follower.',
        points: [
          'Barcelona say: control the ball and the game follows.',
          'Man City say: control the space and the ball follows.',
          'Madrid say: control the moment and neither of the others matters.',
          'Arsenal and Kasi say: none of it counts if the player is too scared to be himself.',
          'All four are winning football. The skill is knowing which one this Saturday, against this opponent, needs.',
        ],
        say: { script: 'If a coach ever tells you there is one right way to play football, he has stopped learning. Our model picked four teachers on purpose, and they argue with each other. Your job is to be able to do more than one of them.',
          ask: 'Next opponent. Which of the four do we need most, and why?',
          cue: 'Pick the tool for the day.' },
        note: 'Present this one last. It only works once the boys believe the first four.' },
    ],
    sources: [
      'K1 Shooters Academy Youth Development Model (club document) — the four pillars.',
      'Transition play and low-block counter-attacking as described in public tactical analysis of Real Madrid.',
    ],
  });

})(window.K1 = window.K1 || {});
