/* K1 Shooters club app — masterclass content.
 * Built on the K1 SHOOTERS ACADEMY YOUTH DEVELOPMENT MODEL, extended with the 4-2-2-2 work
 * of Roberto De Zerbi and Cesc Fàbregas. Each entry is a talk the coach presents to the team. */
(function (K1) {
  'use strict';
  const R = mc => K1.Masterclass.register(mc);

  /* ============================================================ THE K1 WAY */
  R({
    id: 'k1-way', group: 'K1 game model', title: 'The K1 Way',
    subtitle: 'Who we are before we talk about any shape', coach: 'K1 Shooters Academy',
    level: 'Every age group', duration: '25 min', accent: '#f5b301',
    summary: 'Our development model says it plainly: Barcelona’s brain, Arsenal’s swagger, Man City’s structure, and Kasi fire. Everything else in this app — every shape, every drill, every masterclass — is only a way of doing those four things on a Saturday.',
    sessionIds: ['k1_rondo_5v2', 'k1_press_4plus2v3', 'k1_buildup_6v5'],
    slides: [
      { kind: 'chapter', title: 'Skill. Smarts. Swagger.', lead: 'The road to K1 Shooters FC.' },
      { title: 'What we are building', lead: 'Intelligent, expressive, disciplined footballers who play bold, tactical football rooted in global excellence and township resilience.',
        points: [
          'Barcelona’s brain — game intelligence, positional play, decisions.',
          'Arsenal’s swagger — creative expression, flair, confidence on the ball.',
          'Man City’s structure — tactical discipline, build-up precision, collective pressing.',
          'Kasi fire — township grit and ambition. We never lose the street edge.',
        ],
        quote: { text: 'Street meets structure.', by: 'K1 Shooters Academy development model' },
        note: 'Ask the group which of the four they are strongest in, and which one they owe the team.' },
      { title: 'The pathway', lead: 'Four stages, and every boy knows which one he is in.',
        points: [
          'Foundation, U7 to U11 — ball mastery, freedom, joy. Fall in love with the ball.',
          'Formation, U12 to U15 — game intelligence and creativity. Understand space and combinations.',
          'Performance, U16 to U19 — tactical readiness and structure. Learn systems and match preparation.',
          'Transition, U19 and up — earn your place in K1 Shooters FC.',
        ],
        coaching: ['Name the stage a boy is in when you correct him', 'A U9 mistake and a U17 mistake are not the same mistake', 'Never coach a Foundation player like a Performance player'] },
      { title: 'Our tactical identity', lead: 'Four sentences from our own model. Learn them by heart.',
        points: [
          'Build from the back — calm and structured, starting with the goalkeeper, to draw them out and open the lanes.',
          'Exploit the space between the lines — the gap between their midfield and their defence is our danger zone.',
          'Attack in waves — vertical movement, rotation in midfield, intelligent third-man runs.',
          'Thrive under pressure — we bait them, then we break them.',
        ],
        quote: { text: 'We bait them, then break them.', by: 'K1 Shooters Academy development model' },
        board: { formation: '433', away: '442low', pitch: 'full', overlay: 'lanes' },
        note: 'That last line is the whole reason we are studying De Zerbi and Fàbregas. We already believe it — now we learn the mechanics.' },
      { title: 'The bridge: full-backs and anchors', lead: 'Our model names these two roles as the bridge between defence and attack.',
        points: [
          'Full-backs: read the game, offer the safe option in build-up, then decide — go outside, or come inside as the extra man.',
          'Anchors (our 6 and 8): scan early, protect the centre-backs, and always offer a forward angle.',
          'Between them they decide whether we play forward, switch, or reset. Nobody else has that job.',
        ],
        board: { drill: 'k1_role_fullback' },
        caption: 'One picture, two answers: invert or overlap.',
        coaching: ['Look at your winger before you look at the ball', 'Anchor: two scans before every reception', 'Shout your choice so the man behind you can cover'] },
      { title: 'Our week', lead: 'Every day has a name and a job.',
        points: [
          'La Masia Mondays — build-up and scanning, on a 4-2 base.',
          'Arsenal Tuesdays — 1v1s, flair, shooting, final-third rotations.',
          'Workshop Fridays — the tactical board and individual roles.',
          'Tactical Saturdays — U17s join K1 Shooters FC. Systems and scenarios.',
        ],
        note: 'All four are in the Sessions tab as ready-made plans. Open one, change the minutes, print it.' },
      { title: 'How to lay the week out', lead: 'If we play Saturday, the best three nights are Tuesday, Wednesday and Thursday. That is not a preference, it is the structure.',
        points: [
          'Three days before the match: small spaces, short sharp reps, long rests. Rondos and tight zone games.',
          'Two days before: the big session. Large spaces, long reps, many players, closest to the real game.',
          'One day before: short, fast, high quality, low volume. Patterns, finishing, sprints, set pieces. Confidence, not fatigue.',
          'If we only get two nights, keep the sharp night and make the other a hybrid. The match itself gives us the long one.',
        ],
        coaching: ['A 90-minute session gives about 60 minutes of real work — plan for that, not for 90', 'Progress by complexity, not by volume: same reps, one more rule', 'Keep the sprint night sharp. Amateur weeks reach less than half of match sprinting, and nothing else replaces it.'],
        note: 'Our four named days already do this. La Masia Monday is the tight session, Tuesday the expressive one, Friday the board and roles, Saturday the full system.' },
      { title: 'The K1 language of play', lead: 'Same words from U11 to the first team.',
        points: [
          '“Half-space” — the lane between the centre and the touchline.',
          '“Bait” — stand still on the ball on purpose to invite a presser.',
          '“Free man” — the player their press has stopped covering.',
          '“Third man” — the one who receives because someone else was marked.',
          '“Bridge” — our full-backs and anchors.',
          '“Five seconds” — how long we have to win it back.',
        ],
        coaching: ['Use the same six words at every age group', 'If a boy cannot say the word, he cannot use the idea', 'Make them say it back to you, not nod'] },
    ],
    sources: [
      'K1 Shooters Academy Youth Development Model (club document).',
      'Keep learning: Modern Football Analyst on YouTube — positional play and modern tactical concepts.',
      'GEDFOOTBALL on YouTube — build-up direction and coaching detail.',
      'The Coaches’ Voice — Fàbregas “Building up to attack” masterclass, taught in a 4-2-2-2.',
    ],
  });

  /* =========================================================== FOUNDATIONS */
  R({
    id: 'positional-foundations', group: 'Foundations', title: 'The five lanes',
    subtitle: 'Why we stand where we stand', coach: 'Positional play',
    level: 'U11 and up', duration: '20 min', accent: '#38bdf8',
    summary: 'Before any system, the team needs a shared map of the pitch. Five vertical lanes, three horizontal zones, and rules about who may stand where. Everything else sits on top of this.',
    sessionIds: ['k1_rondo_5v2', 'positional_4v4_3', 'y_passing'],
    slides: [
      { kind: 'chapter', title: 'The map', lead: 'Two touchlines, five lanes, three zones. Learn the map and the game slows down in your head.' },
      { title: 'Five lanes across the pitch', lead: 'Two wide lanes on the touchlines, two half-spaces, one central lane.',
        points: [
          'The half-spaces are the lanes between the centre and the touchline. Most goals in modern football are created from there.',
          'Rule one: never two of us in the same lane at the same height. One steps forward, or moves across.',
          'Rule two: at least one of us in every lane when we attack, so they must defend the whole width.',
        ],
        coaching: ['Ask a player where he is standing before you tell him', 'Name the lane out loud: “half-space, Thabo”', 'If two are in one lane, the deeper one moves'],
        board: { formation: '433', away: '442low', pitch: 'full', overlay: 'lanes' },
        caption: 'The shaded strips are the half-spaces.' },
      { title: 'Three lines, never flat', lead: 'Someone behind the ball, someone level, someone beyond. That is a triangle.',
        points: [
          'The man on the ball should see two easy options and one brave one.',
          'If we stand in a line, one defender blocks two of us with one body.',
          'When you cannot see a triangle around the ball, that is your cue to move.',
        ],
        coaching: ['Freeze the game: how many triangles can you see?', 'Support at an angle, never in a straight line', 'Too close and one defender covers both of you'],
        board: { drill: 'positional_4v4_3' } },
      { title: 'The third man', lead: 'The player who receives is often not the one the pass was aimed at.',
        points: [
          'A to B, B sets to C. C had time because B held the defender.',
          'The third man is the one watching, not the one shouting.',
          'This is how we beat a man-to-man press: the free man is one pass further than they are looking.',
        ],
        coaching: ['Check away before you receive', 'Set with the first touch', 'Start your run as the first pass travels'],
        board: { drill: 'y_passing' } },
      { title: 'The five seconds after we lose it', lead: 'Those five seconds decide whether the map still works.',
        points: ['Nearest man presses immediately, he does not wait for help.', 'The next two cut the two easiest passes.', 'Everyone else recovers towards our own goal, not sideways.'],
        coaching: ['Count the five seconds out loud in training', 'Press the ball, block the pass, recover the shape', 'If we cannot win it in five, we drop and organise'],
        board: { drill: 'transition_4v4_2' } },
    ],
    sources: ['Standard positional-play principles used across the modern game.'],
  });

  /* ============================================================= THE SHAPE */
  R({
    id: 'the-4222', group: '4-2-2-2', title: 'The magic square',
    subtitle: 'What a 4-2-2-2 is, and what it demands', coach: 'The 4-2-2-2',
    level: 'U13 and up', duration: '30 min', accent: '#a855f7',
    summary: 'Our model’s shapes are 4-2-3-1 and 4-3-3. The 4-2-2-2 is a variation on the same beliefs, not a replacement: a square of four in midfield, two strikers, and nobody starting on the touchline. That last part changes everybody’s job.',
    sessionIds: ['k1_press_4plus2v3', 'k1_pattern_fb_pivot', 'k1_buildup_6v5'],
    slides: [
      { kind: 'chapter', title: 'A square, not a line', lead: 'Two sixes, two tens, two nines — and two full-backs who must own the touchline alone.' },
      { title: 'The shape', lead: 'Four defenders, a double pivot, two tens in the half-spaces, two strikers.',
        points: [
          'The two tens do not start wide. They live in the half-spaces, between their midfield and their defence.',
          'The two strikers split the centre-backs and pin the back line so the tens can breathe.',
          'Because nobody starts wide, the full-backs are the only width we have. If they do not go, we are narrow and easy to defend.',
        ],
        board: { formation: '4222dz', away: '4141mid', pitch: 'full', overlay: 'lanes' },
        caption: 'The square: 6, 8, 7, 10. Width from 2 and 3 only.',
        coaching: ['Tens: if you can see the touchline in front of you, you are too wide', 'Strikers: pin, do not drop, until the ball is ready', 'Full-backs: the touchline is yours and only yours'] },
      { title: 'What each player owns', lead: 'Individual jobs, phase by phase. Say your own out loud.',
        points: [
          'Goalkeeper — the extra man. Invite the press, release the free man, play forward when the picture is on.',
          'Centre-backs — split wide of the keeper, carry the ball forward, and be brave enough to stand still on it.',
          'Full-backs (2, 3) — width in build-up, then choose: overlap outside or invert inside.',
          'Anchors (6, 8) — one drops or shows, the other stays. Never both in the same place.',
          'Tens (7, 10) — receive between the lines on the half turn, then attack the box.',
          'Strikers (9, 11) — one goes long, one comes short. Never both the same.',
        ],
        coaching: ['Every pair has an “if you go, I stay” rule', 'If two players want the same space, the deeper one gives way', 'Say your job before the session, not after the mistake'] },
      { title: 'How it becomes something else', lead: 'The shape on the teamsheet is only the starting position.',
        points: [
          'In build-up it becomes a 2-4-4 or a 3-2-5: the full-backs step up, or one tucks in beside the centre-backs.',
          'Out of possession it becomes a 4-4-2: the two tens drop onto the flanks and we have two banks of four.',
          'Same eleven players, three different pictures, one set of rules.',
        ],
        board: { morph: 'dezerbi_4222' },
        caption: 'Press Play on the board to watch the shape change.',
        note: 'Open this on the board and play it in front of the team. Watching it move teaches more than any diagram.' },
      { title: 'The price of the shape', lead: 'Every system costs something. Name the cost so nobody is surprised.',
        points: [
          'No natural wingers means the full-backs run further than anybody. They must be fit and they must be brave.',
          'Two strikers and two tens high up means fewer bodies behind the ball on a counter.',
          'It asks a lot of the two anchors — if they are beaten, the back four is exposed quickly.',
        ],
        quote: { text: 'I prefer to lose even with this deserved result than do that.', by: 'Cesc Fàbregas', source: 'after losing 4-0 at Inter, December 2025' },
        note: 'Fàbregas was asked whether he considered going defensive against Inter. He said no, and said it publicly. Teaching boys that a system has a price, and that the coach chose to pay it, is more honest than pretending it has none.' },
    ],
    sources: ['Coaches’ Voice · MÁS Positional · Total Football Analysis · Between The Posts.'],
  });

  /* ============================================================= BUILD-UP */
  R({
    id: 'build-up', group: 'Phases of play', title: '1 · Build-up',
    subtitle: 'Bait them, then break them', coach: 'De Zerbi · Fàbregas',
    level: 'U13 and up', duration: '30 min', accent: '#22c55e',
    summary: 'Our model already says it: we thrive under pressure, we bait them and then we break them. This is how that actually works — the free man is created by arithmetic, not by skill.',
    sessionIds: ['k1_rondo_5v2', 'k1_press_4plus2v3', 'k1_buildup_6v5', 'k1_zone_buildup'],
    slides: [
      { kind: 'chapter', title: 'Why play out at all?', lead: 'Not to look good. To move them. Every player who comes to press us leaves a space behind him.' },
      { title: 'The principle', lead: 'A press is a decision by them. We make that decision as expensive as possible.',
        points: [
          'If they do not press, we carry the ball forward until they do.',
          'If they do press, they have left somebody free. Our job is to find him before they recover.',
          'We are not playing out to keep the ball. We are playing out to create a free man higher up.',
        ],
        quote: { text: 'The goalkeeper draws the pressure onto himself and then releases it to the free man.', by: 'Como match-analysis dossier', source: 'Italian Association of Match Analysts, December 2025' } },
      { title: 'The trap: stand still on the ball', lead: 'De Zerbi’s signature. The stillness is the invitation.',
        points: [
          'Centre-back takes the ball, puts his sole on it, and stops. Head up. Feet still.',
          'He does not pass until he sees the presser’s weight go forward.',
          'The moment the presser commits, the ball goes past him — and that man is now out of the game.',
        ],
        board: { phase: 'ph_build_trap' },
        caption: 'Three frames: bait · release · break the line.',
        coaching: ['Sole on the ball, not a touch every second', 'Wait for his weight, not for his shout', 'The pivot shows on the diagonal, never straight behind the presser', 'Everyone beyond the ball holds their height until the line is broken'],
        note: 'Boys will hate this at first. It feels dangerous. Do it in a rondo before you do it in a game.' },
      { title: 'The arithmetic: make a free man', lead: 'Against man-to-man marking you do not need a trick. You need one more body than they have.',
        points: [
          'Centre-backs split wide of the goalkeeper, so their first line has further to run.',
          'One anchor drops in beside them — now we have four builders against three pressers.',
          'They run out of markers. Usually it is the far centre-back who ends up free.',
        ],
        board: { phase: 'ph_build_gk' },
        caption: 'The keeper is the only player they cannot mark.',
        quote: { text: 'With the goalkeeper, you are plus one in every situation.', by: 'Jean Butez', source: 'Como goalkeeper' },
        coaching: ['Count their pressers out loud before the goal kick', 'Split wide — square with the keeper helps them, not us', 'Keeper: first touch forward, into the space the presser left'] },
      { title: 'Two ways our anchors help', lead: 'Fàbregas teaches two, and picks by opponent. So do we.',
        points: [
          'Variation A — one anchor drops to the side of the centre-backs. Safer, keeps four defenders behind the ball, better if they counter well.',
          'Variation B — one anchor drops between the centre-backs to make a back three. Frees both full-backs to fly, but leaves us thinner through the middle.',
          'The coach picks before the game. The players do not choose it mid-match.',
        ],
        board: { formation: '325dz', away: '433press', pitch: 'full' },
        caption: 'Variation B: back three, both full-backs high.',
        coaching: ['Only one anchor drops. Ever.', 'The one who stays takes the space in front of the ball', 'If a full-back goes, somebody covers his lane — say who'] },
      { title: 'Build-up direction', lead: 'Before the first pass, decide which side we are building towards. Then make them believe it is the other one.',
        points: [
          'Every build-up has a direction. If nobody chooses it, eleven players choose eleven different ones.',
          'The centre-back’s body shape points the direction. Open your hips to the side you intend to go.',
          'We attract on one side with short passes, and we finish on the far side. The overload is the lie, the switch is the truth.',
          'The goalkeeper decides the direction on a goal kick, and he says it out loud before he places the ball.',
        ],
        board: { phase: 'ph_prog_switch' },
        caption: 'Attract right, finish left.',
        coaching: ['Call the side before the restart', 'Open your body to the direction you want, close it to the one you do not', 'The far full-back and far ten must hold their width or there is nothing to switch to', 'Two or three passes on the near side is not enough to move them — make it five'],
        note: 'Prompted by “Build up direction” on the GEDFOOTBALL channel. The idea is simple and it is the one thing most youth teams never agree on before kick-off.' },
      { title: 'When not to play out', lead: 'Playing out is a tool, not a religion.',
        points: [
          'If the picture is not on, the keeper goes long to a striker and we fight for the second ball.',
          'Two players attack the drop, the anchors arrive underneath for the loose ball.',
          'Going long on purpose is a decision. Going long in panic is a mistake. They look the same to the crowd and completely different to us.',
        ],
        board: { setpiece: 'gk_long' },
        coaching: ['Call “long” early so the strikers can set', 'Nearest two players to the drop attack it', 'Anchors under the ball, never behind it'] },
    ],
    sources: ['Coaches’ Voice · Between The Posts (April 2026) · Italian Association of Match Analysts dossiers · Opta Analyst.'],
  });

  /* ========================================================== PROGRESSION */
  R({
    id: 'progression', group: 'Phases of play', title: '2 · Progression',
    subtitle: 'Through the lines, not around them', coach: 'Phases of play',
    level: 'U13 and up', duration: '25 min', accent: '#0ea5e9',
    summary: 'We have beaten their first line. Now we have to get through their midfield. Two tools: the third man, and the switch.',
    sessionIds: ['y_passing', 'k1_pattern_fb_pivot', 'k1_role_pivot'],
    slides: [
      { kind: 'chapter', title: 'The middle third', lead: 'This is where good teams get stuck. We have two answers ready.' },
      { title: 'Answer one: the third man', lead: 'Play into a marked man on purpose, and use the man who was watching.',
        points: [
          'The ball goes into the striker who has come short. He is marked, and that is fine.',
          'He sets it first time to the anchor. His marker is now facing the wrong way.',
          'The anchor hits the ten who started running when the first pass travelled.',
        ],
        board: { phase: 'ph_prog_third' },
        caption: 'In · set · forward. Three passes, one line gone.',
        coaching: ['The receiver plays one touch, back the way he came', 'The third man moves on the FIRST pass', 'Set to the far foot so he can play it first time', 'Call the name of the man you are setting to'] },
      { title: 'Answer two: overload, then switch', lead: 'Pull them across, then punish the side they left.',
        points: [
          'Five or six passes on one side before anyone even looks up to switch.',
          'The switch is one long pass, not three short ones — short ones let them slide.',
          'The far ten and the far full-back must have stayed wide and high. If they drifted in to watch the ball, there is nothing to switch to.',
        ],
        board: { phase: 'ph_prog_switch' },
        caption: 'Overload right, finish left.',
        coaching: ['Far side: stay wide, stay high, stay patient', 'Receiver takes his first touch forward, into the space', 'One switch is worth ten square passes'] },
      { title: 'The anchor’s three answers', lead: 'Every time our 6 or 8 receives with a man behind him, he picks one of three.',
        points: [
          'Turn out of it — if his first touch can take him away from the pressure.',
          'Set it back and go again — if the presser is tight on his back. Never turn into a man.',
          'Switch it first time — the best pass he owns, and the one we practise least.',
        ],
        board: { drill: 'k1_role_pivot' },
        coaching: ['Two scans before it arrives: left shoulder, right shoulder', 'Feel the pressure, then touch away from it', 'If in doubt, set and reposition — do not gamble in front of our own goal'] },
    ],
    sources: ['Coaches’ Voice · Total Football Analysis · club practice.'],
  });

  /* ============================================================= CREATION */
  R({
    id: 'creation', group: 'Phases of play', title: '3 · Creation',
    subtitle: 'The final third, where swagger is allowed', coach: 'Phases of play',
    level: 'U13 and up', duration: '25 min', accent: '#ec4899',
    summary: 'Structure gets us here. From here we want courage. Our model calls it Arsenal’s swagger — creative expression inside a shape everyone understands.',
    sessionIds: ['k1_waves_1v1_2v1', 'overlap_pattern', 'crossing_finishing_fullpitch'],
    slides: [
      { kind: 'chapter', title: 'Inside and outside at the same time', lead: 'Give the defender two problems and let him solve only one.' },
      { title: 'The pocket and the overlap', lead: 'One of us receives inside, one of us runs outside. The defender must choose.',
        points: [
          'The ten checks away, then comes back into the gap between their midfield and defence.',
          'He receives on the half turn — back foot, shoulder open, already facing forward.',
          'The full-back goes outside him, early and all the way. If the defender follows the ten, the outside is free. If he stays, the ten turns.',
        ],
        board: { phase: 'ph_create_pocket' },
        caption: 'Two problems, one defender.',
        coaching: ['Check away before you come back — movement buys the metre', 'Receive on the half turn, never square', 'Full-back: go early and do not slow down at the line', 'If they follow the ten, the space behind is the striker’s'] },
      { title: 'Three against two on the flank', lead: 'Ten inside, full-back outside, striker pinning. Get to the by-line.',
        points: [
          'Three players, three different heights. Never level with each other.',
          'Pass and move past — a pass without movement is a dead end.',
          'The cut-back goes to the penalty spot, not across the face of goal.',
        ],
        board: { phase: 'ph_create_wide3v2' },
        caption: 'Overlap · by-line · cut-back.',
        coaching: ['Never level with your team-mate', 'One striker always checks back for the pull-back', 'Cut-backs are the highest-scoring cross in football — practise them most'] },
      { title: 'Where swagger belongs', lead: 'Take people on here. This is the third of the pitch where losing the ball is cheap.',
        points: [
          'In our own third, keep it. In the middle third, move it. In their third, risk it.',
          'A 1v1 in their box is worth more than a safe square pass.',
          'If you take a man on and lose it, the counter-press is already set behind you.',
        ],
        board: { drill: 'k1_waves_1v1_2v1' },
        quote: { text: 'Attack with courage. Express with structure.', by: 'K1 Shooters Academy', source: 'Arsenal Tuesdays' },
        coaching: ['Attack him at speed, then change speed', 'First touch past his standing foot', 'Losing the ball trying is not a mistake here'] },
    ],
    sources: ['K1 Shooters Academy development model · Coaches’ Voice.'],
  });

  /* ============================================================ FINISHING */
  R({
    id: 'finishing', group: 'Phases of play', title: '4 · Finishing',
    subtitle: 'Five runs, five places, nobody guessing', coach: 'Phases of play',
    level: 'U11 and up', duration: '20 min', accent: '#f97316',
    summary: 'The most common reason good build-up produces no goals is that nobody agreed who goes where. Five jobs in the box, decided before the cross leaves the foot.',
    sessionIds: ['k1_waves_1v1_2v1', 'finishing_circuit', 'crossing_finishing_fullpitch'],
    slides: [
      { kind: 'chapter', title: 'Fill the box on purpose', lead: 'If everyone knows his place, the ball only has to find one of them.' },
      { title: 'The five jobs', lead: 'Near post, far post, penalty spot, edge of the box, and the far full-back arriving.',
        points: [
          'Near post — attack it first and attack it early. You are the one who beats the keeper to it.',
          'Far post — start wide of the last defender and arrive late.',
          'Penalty spot — the striker who checks back is usually the free one.',
          'Edge of the box — one player for the second ball, every single time.',
          'Far full-back — arrive for the ball that crosses everybody.',
        ],
        board: { phase: 'ph_finish_box' },
        caption: 'Five zones, five names, agreed before the cross.',
        coaching: ['Nobody stands still when the ball is crossed', 'Attack the ball, do not wait for it', 'The far post starts wide, not central'] },
      { title: 'Second balls and going home', lead: 'Every attack ends in a goal, a second ball, or their counter. Plan for all three.',
        points: [
          'Two players at the edge of the box for the rebound.',
          'Two centre-backs and one anchor stay behind the ball. That is our rest defence.',
          'The far full-back tucks in while the near one crosses.',
        ],
        board: { phase: 'ph_finish_rebound' },
        caption: 'Rest defence: three plus the keeper, always.',
        coaching: ['Nobody watches the shot — follow it in', 'Rest defence is not punishment, it is the reason we can attack', 'Say the rest-defence trio out loud before kick-off'] },
      { title: 'The honest bit about finishing', lead: 'Possession does not score goals. Shots from good places score goals.',
        points: [
          'A team can dominate the ball and still take its shots from bad places.',
            'Two questions after every attack: was the shot from inside the box, and was it from the middle?',
          'Practising finishing under fatigue is worth more than practising it fresh.',
        ],
        note: 'Como led Serie A for possession in 2025-26 and still took the second-highest share of shots from outside the box. Dominating the ball is not the same as creating a good chance. Say that to the boys — it keeps them honest.' },
    ],
    sources: ['Opta Analyst (November 2025) · club practice.'],
  });

  /* =========================================================== HIGH PRESS */
  R({
    id: 'high-press', group: 'Out of possession', title: '5 · The high press',
    subtitle: 'Show him the pass we want him to make', coach: 'Out of possession',
    level: 'U13 and up', duration: '25 min', accent: '#ef4444',
    summary: 'Our model calls for a midfield-led pressing structure with traps in wide areas. A press is not running harder. It is standing in the right place so that the only easy pass is the one we have prepared for.',
    sessionIds: ['press_trap_433', 'transition_4v4_2', 'k1_press_4plus2v3'],
    slides: [
      { kind: 'chapter', title: 'Pressing is a trap, not a chase', lead: 'We do not win the ball where he has it. We win it where we send it.' },
      { title: 'Curve the run', lead: 'The striker’s body decides which pass is available.',
        points: [
          'Run at the centre-back on a curve so your body blocks the inside pass.',
          'Now the only comfortable ball is out to the full-back. That is exactly what we want.',
          'Nobody else moves until that pass is made. Jumping early breaks the trap.',
        ],
        board: { phase: 'ph_press_high' },
        caption: 'Curved run · the trigger · the trap closes.',
        coaching: ['Press the man, block the pass — both at once', 'The trigger is the pass to the full-back', 'Never two players pressing the same man'] },
      { title: 'When it goes wide, everybody jumps', lead: 'One trigger, five reactions, at the same moment.',
        points: [
          'The ten presses from the outside in, pinning him to the touchline.',
          'Our full-back steps up onto their winger — high and early.',
          'The near anchor covers the inside pass. The far side slides across and tucks in.',
          'The touchline is our extra defender. Use it.',
        ],
        coaching: ['Press from the outside in, never from inside out', 'Full-back: step up before the ball arrives, not after', 'Far side tucks in — the ball cannot reach that far quickly'] },
      { title: 'The price of pressing high', lead: 'Say it honestly so nobody is shocked when it happens.',
        points: [
          'A high press means a high line. A high line means space behind.',
          'Good teams will go long over the press. That is not our mistake, that is the deal.',
          'Our answer: the keeper sweeps, and we accept one or two chances against in exchange for many won high up.',
        ],
        quote: { text: 'If you go and press high against Barcelona with Xavi, Iniesta and Messi, you are doing the same thing, just against very strong opponents.', by: 'Cesc Fàbregas', source: 'December 2025' },
        note: 'Como pressed harder than any team in Europe’s big five leagues in 2025-26 and finished fourth. They also lost 4-0 at Inter doing it. Both facts are true and the boys should hear both.' },
    ],
    sources: ['Opta Analyst · Coaches’ Voice · Italian Association of Match Analysts.'],
  });

  /* ==================================================== BLOCKS & COUNTER */
  R({
    id: 'blocks-counter', group: 'Out of possession', title: '6 · Mid block, low block, counter',
    subtitle: 'When we do not press, we organise', coach: 'Out of possession',
    level: 'U13 and up', duration: '30 min', accent: '#64748b',
    summary: 'We cannot press high for ninety minutes and no team should try. Two organised blocks, and the counter attack that is the whole reason we defend deep at all.',
    sessionIds: ['def_shape_shadow', 'press_trap_433', 'transition_4v4_2'],
    slides: [
      { kind: 'chapter', title: 'Give them the ball, not the space', lead: 'Two blocks, one rule: we slide together or we do not slide at all.' },
      { title: 'Mid block — two banks of four', lead: 'We defend from halfway. The two tens drop onto the flanks.',
        points: [
          'Ten metres between the lines. Ten metres between each player in a line.',
          'Slide as the ball moves, not after it arrives.',
          'The far winger tucks into the middle. The strikers stand in the shadow of their anchor.',
        ],
        board: { phase: 'ph_block_mid' },
        caption: 'Slide together, trap on the touchline.',
        coaching: ['If you can read his number, you are close enough', 'The whole block moves as one body', 'Nobody dives in until the ball is on the touchline'] },
      { title: 'Low block — protect the middle of the goal', lead: 'Deep and narrow. They can have the wide areas.',
        points: [
          'Narrow first, wide second. The goal is in the middle.',
          'Nobody runs out of the line unless the ball is in front of him.',
          'In the box: head on a swivel, see the ball and see your man.',
          'Clear it long and wide, never square across our own box.',
        ],
        board: { phase: 'ph_block_low' },
        coaching: ['Narrow, narrow, narrow — then react wide', 'One man attacks the cross, the rest mark inside out', 'A clearance that goes out for a throw is a good clearance'] },
      { title: 'The counter — three passes to their goal', lead: 'This is why we defended deep. Now all that space in front of us belongs to us.',
        points: [
          'First pass forward if it is on. A sideways pass kills the counter.',
          'The first runner goes beyond the ball, not towards it.',
          'Two men commit to the box. The rest stop the counter to our counter.',
          'Five seconds: if it is not a shot by then, keep the ball and rebuild.',
        ],
        board: { phase: 'ph_counter' },
        caption: 'Win it deep · first pass forward · two in the box.',
        coaching: ['Look forward before you look up', 'Runner goes beyond, never to feet', 'Nobody sprints 60 metres to arrive and stop — finish the run'] },
    ],
    sources: ['Club practice · Coaches’ Voice.'],
  });

  /* ======================================================= THE COACH STUDY */
  R({
    id: 'fabregas-como', group: 'Coach studies', title: 'Fàbregas at Como',
    subtitle: 'As many solutions as possible', coach: 'Cesc Fàbregas',
    level: 'Coaches and U16+', duration: '30 min', accent: '#1d4ed8',
    summary: 'Fàbregas took Como from Serie B to the Champions League. His own coaching masterclass, “Building up to attack”, is taught in a 4-2-2-2 — which is why you keep seeing that shape attached to his name. But he has publicly refused to be a one-system coach, and that refusal is the real lesson.',
    sessionIds: ['k1_press_4plus2v3', 'k1_zone_buildup', 'k1_role_pivot'],
    slides: [
      { kind: 'chapter', title: 'From Serie B to the Champions League', lead: 'Promotion in 2024. Tenth in 2025. Fourth and a Champions League place in 2026, above Milan and Juventus.' },
      { title: 'First, a correction worth making', lead: 'The 4-2-2-2 is how he teaches, not how Como line up.',
        points: [
          'Como’s teamsheet shape across both Serie A seasons is a 4-2-3-1. In games it becomes a 4-3-3, a 4-2-2-2, or even a back three.',
          'His Coaches’ Voice masterclass, “Building up to attack”, is built on a 4-2-2-2 and walks through every role — goalkeeper, centre-backs, full-backs, pivots, the free man, the third man.',
          'So the 4-2-2-2 is his teaching frame. Use it the same way we are using it: a clear scaffold for explaining jobs.',
        ],
        quote: { text: 'I don’t want to be the coach that always has the same way of playing. You need to have as many solutions as possible.', by: 'Cesc Fàbregas', source: 'February 2026' },
        board: { formation: '4222como', away: '442', pitch: 'full' },
        caption: 'The teaching shape: one ten free, one holding the far half-space.' },
      { title: 'The build-up, in three mechanisms', lead: 'Nothing here is a trick. It is all counting.',
        points: [
          'Centre-backs split wide onto the goalkeeper so their first line has further to run.',
          'The goalkeeper is a real footballer — with him, Como get up to seven players into the build-up.',
          'One pivot drops in. Against man-to-man marking they run out of markers, and the far centre-back is free.',
        ],
        board: { phase: 'ph_build_gk' },
        quote: { text: 'With the goalkeeper, you are plus one in every situation.', by: 'Jean Butez', source: 'Como goalkeeper' },
        coaching: ['Count the pressers before the goal kick', 'Split wide, never square with the keeper', 'The free man is created by arithmetic, not by skill'] },
      { title: 'Freedom, paid for with work', lead: 'Nico Paz gets more freedom than anyone at Como. Look at what he owes for it.',
        points: [
          'His freedoms: roam between the lines, drift wide, drop deep, receive facing his own goal and turn.',
          'His obligations: scan constantly before receiving, press the opposition playmaker, and be one of the team’s top four in defensive duels.',
          'That is the deal. Freedom is bought with work, and every boy who wants the first one must accept the second.',
        ],
        quote: { text: 'There are some players you need to be more structured with, and others who are more talented and you can give more freedom.', by: 'Cesc Fàbregas', source: 'September 2026, after Como beat RB Leipzig 4-1' },
        coaching: ['Name the boy in your team who has earned freedom, and say why', 'Sell the obligations as loudly as the freedoms'] },
      { title: 'Without the ball', lead: 'The part most people miss: Como defend harder than they pass.',
        points: [
          'A 4-4-2 with the playmaker joining the striker as the first line of pressure.',
          'Triggers: a back-to-goal reception, a backward or sideways pass, a heavy touch.',
          'When they lose it, four or five players swarm the ball inside five or six seconds.',
          'They press man to man and seek duels, which is why they make many fouls and few interceptions.',
        ],
        board: { phase: 'ph_press_high' },
        note: 'Opponents advance up the pitch more slowly against Como than against any other side in Serie A. That is what a good press actually buys you.' },
      { title: 'What it costs him', lead: 'Teach the weaknesses. It makes the strengths believable.',
        points: [
          'A high line concedes space behind, and good teams go long over the press.',
          'Too many bodies ahead of the ball when an attack breaks down.',
          'Plenty of possession, but too many shots from outside the box.',
          'A young team that can lose control of a chaotic game.',
        ],
        quote: { text: 'Mistakes are part of the game. They can often help you grow faster.', by: 'Cesc Fàbregas', source: 'April 2026' } },
      { title: 'What we take from him', lead: 'Three things that transfer straight to a township academy.',
        points: [
          'Build the house from the ground up — principles, behaviours, discipline, respect, hard work. He learned that from Wenger.',
          'Have more than one solution. The shape is a tool, not an identity.',
          'Say the price of your football out loud, and pay it on purpose.',
        ],
        quote: { text: 'Like Arsène Wenger used to say, you always need to build the house from the ground up. You cannot build a house from the roof.', by: 'Cesc Fàbregas' } },
    ],
    sources: [
      'Coaches’ Voice masterclass “Building up to attack” (Fàbregas, c. 2023) and Como tactics profile (October 2025).',
      'Opta Analyst, November 2025 · Between The Posts, April 2026 · MÁS Positional, April 2026.',
      'Italian Association of Match Analysts dossiers, 2024, 2024-25 and 2025-26 · Total Football Analysis.',
      'Quotes: Goal.com, football-italia, beIN Sports, ESPN, 2025-2026.',
    ],
  });

  R({
    id: 'teaching-the-boys', group: 'Coaching the coaches', title: 'Teaching this to boys',
    subtitle: 'What to coach at U9, U11 and U13 — and what to leave alone', coach: 'For the coaching staff',
    level: 'Coaches', duration: '25 min', accent: '#22c55e',
    summary: 'The system is complex. The building blocks are not. The most common mistake an ambitious coach makes is running U13 content with U9s. Here is what belongs at each stage of our pathway, and what must wait.',
    sessionIds: ['dz_rondo_5v2_cone', 'k1_rondo_5v2', 'dz_bait_press'],
    slides: [
      { kind: 'chapter', title: 'Do not push the content down', lead: 'A nine-year-old does not need a three-zone build-up. He needs a thousand first touches under light pressure.' },
      { title: 'U7 to U11 · Foundation', lead: 'Ball mastery, freedom, joy. No positional play yet.',
        points: [
          'Coach: dribbling, 1v1, small games with many goals, and the simplest rondo — 5v2, free touches, big grid.',
          'The one idea from our model a nine-year-old can hold: “freeze and look”. Stop the ball, lift your head, then decide.',
          'Do not coach: the double pivot, the five lanes, rest defence, pressing traps, or baiting a press under real pressure.',
          'At 7v7 use a 2-3-1. It is the same skeleton as our senior shape — two backs, three across, one forward.',
        ],
        board: { drill: 'dz_rondo_5v2_cone' },
        caption: 'The cone in the middle is worth double. That is all the positional play a nine-year-old needs.',
        coaching: ['Never sacrifice the 1v1 — positional play without dribbling makes sideways-passing machines', 'Ask “where was the space?” instead of shouting “pass left”', 'Praise the brave pass that is intercepted more than the safe one'] },
      { title: 'U12 to U15 · Formation', lead: 'Game intelligence and creativity. Now the words go in.',
        points: [
          'Add: positions inside the rondo, the third man named and rewarded, the switch rewarded, the central pass rewarded.',
          'Build-up with a spare man first, then take the spare man away one at a time.',
          'Introduce the square pass as bait — at half pace, with the presser told to press.',
          'At 9v9 use a 3-2-3. The two in the middle are our double pivot, so the boys arrive at 11v11 already knowing the role.',
        ],
        board: { formation: '9-323', away: '9-332', pitch: 'nine' },
        caption: '9v9 3-2-3 — the pivot pair is already there.',
        coaching: ['One new rule per week. Three zones and five rules and nobody knows what is happening', 'Eight words the whole club shares: rondo, positional play, third man, between the lines, width and depth, switch, availability, pressure resistance'] },
      { title: 'U16 to U19 · Performance', lead: 'Now the full model is coachable.',
        points: [
          'The sole-of-the-foot bait under live pressure. The anchor who stays in the shadow and receives off a lay-off.',
          'Counter-press with the “win it back where you lost it” rule. Rest defence as a named structure.',
          'Wide 2v1 into a box 3v2, and the near-post, penalty-spot, back-post arrival.',
          'Pattern play with mannequins, unopposed, then opposed.',
        ],
        board: { drill: 'dz_bait_press' },
        caption: 'The documented De Zerbi build-up practice. Six plus a keeper against two pressers.',
        note: 'Run the build-up on half a pitch plus ten metres, not the full field. Reduce the pitch, never the idea.' },
      { title: 'How to know it is working', lead: 'You can lose 4-2 and still be developing. These are the real markers.',
        points: [
          'In training: rondo sequences get longer even as you shrink the grid.',
          'Boys scan before receiving without being told.',
          'The first touch goes into space instead of back to the passer.',
          'More third-man passes. That is the surest sign of all.',
          'In matches: after winning it they look for a pass, not a clearance — and after a bad pass, the courage does not change.',
        ],
        quote: { text: 'Only in my country is defeat experienced as a tragedy in youth football. And talents often mature late — you have to wait for them.', by: 'Roberto De Zerbi', source: 'Corriere della Sera, October 2025' },
        note: 'Say this to the parents before the season, not after the first 5-1: ball losses are the price of development. If it becomes too painful, make the environment easier — more spare men, a bigger field — do not abandon the idea.' },
    ],
    sources: ['La Masia youth methodology (coach-os) · Player Development Project · FIFA Training Centre elite sessions · Spanish FA U9-12 material.'],
  });

  R({
    id: 'dezerbi-method', group: 'Coach studies', title: 'De Zerbi’s method',
    subtitle: 'Bait the press — and what it costs to play this way', coach: 'Roberto De Zerbi',
    level: 'Coaches and U16+', duration: '30 min', accent: '#7dd3fc',
    summary: 'Sassuolo, Shakhtar, Brighton, Marseille and now Tottenham. Guardiola has called him one of the most influential coaches of the last twenty years. His method is the clearest version of the idea our own model already believes in: bait them, then break them. It is also, right now, visibly hard to run — and that is worth teaching too.',
    sessionIds: ['k1_press_4plus2v3', 'k1_buildup_6v5', 'press_trap_433'],
    slides: [
      { kind: 'chapter', title: 'Stillness as a weapon', lead: 'Most coaches teach players to move the ball quickly. He teaches them to stop it.' },
      { title: 'One correction before we start', lead: 'His team sheet says 4-2-3-1. The 4-2-2-2 is what it becomes when he has the ball.',
        points: [
          'He has never called his shape a 4-2-2-2. Analysts named it, because that is what it looks like in possession.',
          'And his last “2” is not two strikers. It is two wide forwards pinned to the touchlines, with two tens inside them in the half-spaces.',
          'Those two tens set a trap for the centre-backs: come up and the space behind is for the winger, stay down and we have an extra man in midfield. They cannot win.',
        ],
        board: { formation: '4222dzw', away: '442low', pitch: 'full', overlay: 'lanes' },
        caption: 'Two tens inside, two forwards on the touchline.',
        note: 'The classic 4-2-2-2 with two strikers is a different animal, and both are in the Playbook. Know which one you are coaching.' },
      { title: 'The shape', lead: 'A deep double pivot, a goalkeeper who is a footballer, and full-backs who live on the touchline.',
        points: [
          'The goalkeeper plays as an extra centre-back so the full-backs can push high and hold the width.',
          'The double pivot sits very deep and staggered, never level. They are the release valve.',
          'Everything is short — but only until it should not be. He builds to break a press, not to keep the ball.',
        ],
        quote: { text: 'Hoofing the ball and going for the header is gambling. And I do not like to gamble.', by: 'Roberto De Zerbi', source: 'Bobo TV, 2021' },
        board: { formation: '4222dz', away: '433press', pitch: 'full' },
        caption: 'The classic square version: two strikers, width from the full-backs.' },
      { title: 'The signature: stop the ball', lead: 'The centre-back puts his sole on the ball and waits. That stillness is the whole idea.',
        points: [
          'A moving ball tells a presser where to run. A still ball tells him nothing, so he has to commit.',
          'The moment his weight goes forward, the pass goes past him and he is out of the game.',
          'It looks like danger and it is danger. That is why it works — they cannot help themselves.',
        ],
        board: { phase: 'ph_build_trap' },
        caption: 'Bait · release · break the line.',
        quote: { text: 'Boss, when I use the sole, the opponent comes harder to press me. I use the sole to draw him out harder.', by: 'Antonio Vacca, a player of his at Foggia', source: 'retold by De Zerbi in a coaching lesson, 2020' },
        coaching: ['Sole on the ball, head up, feet still', 'Wait for his weight, not for his shout', 'The nearest team-mate must be showing on the diagonal before the bait starts', 'Practise this in a rondo for weeks before you ask for it in a match'],
        note: 'De Zerbi tells this story himself. A player worked it out before the coach did — the sole makes the opponent want to press you harder. That is the bait, explained by the man using it.' },
      { title: 'What the best coach in the world noticed', lead: 'Guardiola, asked about a De Zerbi team, put the whole method in one sentence.',
        points: [
          'It is not about passing quickly. It is about choosing the exact moment.',
          'The ball waits for the opponent to move. Then it goes.',
          'If nobody moves, nothing needs to happen yet. Patience is part of the plan, not a failure to find a pass.',
        ],
        quote: { text: 'They are the master of when to pass to the free man. They move at the right time. They don’t pass the ball until the opponent moves.', by: 'Pep Guardiola', source: 'press conference, May 2023' },
        board: { phase: 'ph_build_gk' },
        caption: 'Wait for the movement. Then find the man it freed.' },
      { title: 'Why bait at all?', lead: 'Because a press is the only way an opponent voluntarily leaves space.',
        points: [
          'If they sit in a block, the space is behind their midfield and it is small.',
          'If we pull them out, the space is behind their defence and it is enormous.',
          'So we invite the press deliberately, and the whole front line holds its height, waiting for the line to break.',
        ],
        note: 'This is the part young players get wrong. They see the team playing out and think the goal is to keep the ball. The goal is to make the opponent move.' },
      { title: 'When to go long — it is arithmetic, not bravery', lead: 'From his own coaching thesis. This is the rule most people miss about him.',
        points: [
          'If they press moderately, we conquer ground gradually and walk them backwards.',
          'If they press hard, we move the ball fast to attract as many of them as possible, then go to the high winger or the wide full-back. The game becomes vertical.',
          'If they match us man for man with no spare player, the goalkeeper goes straight to the forwards. No build-up at all.',
        ],
        quote: { text: 'Reducing football to “building from the back or not” shows a lack of understanding.', by: 'Roberto De Zerbi' },
        board: { setpiece: 'gk_long' },
        coaching: ['Count their pressers, then choose — do not decide by habit', 'Going long on purpose and going long in panic look the same to the crowd and are opposites to us', 'Two players attack the drop, the anchors arrive underneath'],
        note: 'He is not a short-passing ideologue. He reads the numbers and picks. That is the lesson for our boys.' },
      { title: 'What he asks of each player — in his own words', lead: 'From his UEFA Pro Licence thesis at Coverciano. Read these out loud to the group.',
        points: [
          'Goalkeeper — brave, happy with his feet, quick to read. And this: “since we have no codified build-up routines, understanding the right solution becomes vital”.',
          'Centre-backs — brave, ambitious, clean with the inside of the foot, able to read when to step out and when to drop. “They must have the pleasure of holding the reins, knowing it all starts from them.”',
          'Midfielders — quick feet, able to play as the deep pivot and between the lines almost as a ten. “Cheeky, with personality.”',
          'Wide forwards — quick in tight spaces. “Able to hold maximum width, but also to come inside, into the traffic.” They do not need to run far. They need to want the 1v1.',
        ],
        quote: { text: 'Since we have no codified build-up routines, understanding the right solution to take becomes vital.', by: 'Roberto De Zerbi', source: 'UEFA Pro Licence thesis, Coverciano' },
        note: 'That last line is the key to the whole method. He does not teach patterns to memorise. He teaches players how to read. If you coach the patterns as choreography, you have missed it.' },
      { title: 'What it demands of the players', lead: 'This is not a free style. It is an expensive one.',
        points: [
          'Centre-backs with the nerve to be still while a striker sprints at them.',
          'A goalkeeper who is genuinely a footballer, not just a shot-stopper.',
          'Full-backs with the legs to give the width for ninety minutes.',
          'Fitness above everything — the intensity has to last the full game, not the first thirty minutes.',
        ],
        quote: { text: 'You cannot help the team if you are invisible.', by: 'Roberto De Zerbi', source: 'to a substitute after a goalless draw, September 2026' },
        coaching: ['Movement is the job, not a bonus', 'A forward cannot play with his shoulder to the goal — open up before it arrives', 'Every player must be findable at every moment'] },
      { title: 'The price, in numbers', lead: 'Same coach, two clubs, two countries — and the same weakness both times.',
        points: [
          'Brighton conceded more goals from opposition counter-attacks than any other Premier League team, and faced the most fast breaks in the league.',
          'Marseille then conceded the most direct-attack goals in France.',
          'That is not bad luck and it is not bad players. It is what the system costs, and he accepts it openly.',
        ],
        quote: { text: 'If we lose the ball, we can concede a goal. What is the problem? I am the coach, I take the responsibility.', by: 'Roberto De Zerbi' },
        board: { phase: 'ph_counter' },
        caption: 'This is what happens to a team that is caught high. Know it, and set your rest defence.' },
      { title: 'How good teams beat it', lead: 'Teach the counter so our boys recognise it when it is done to us.',
        points: [
          'Refuse the bait. Go fully man to man, or sit deep — never get caught between the two.',
          'Press the double pivot instead of the centre-backs, and block the pass back to the goalkeeper.',
          'Mark the men who drop, and keep one spare defender at the back for the runner in behind.',
          'Congest the middle and make them play the hopeful long ball rather than the chosen one.',
        ],
        note: 'A rival manager’s rule is the clearest line on this: go fully high man to man, or stay deep, but never in the middle, or they will play around you.' },
      { title: 'The honest part', lead: 'Right now the method is straining, and the boys should hear it.',
        points: [
          'At Tottenham he has not scored in his opening four league games — the worst start in the club’s history by that measure.',
          'He has said plainly that the squad cannot yet sustain his intensity for ninety minutes, and blamed a broken pre-season.',
          'When he arrived into a relegation fight, he dropped the baiting himself and said he had no time for principles or build-up. He kept the pressing and the intent.',
        ],
        note: 'This is the most valuable slide here. A method is not magic. It needs conditioning, repetitions and time — and even a coach Guardiola calls one of the most influential of the last twenty years is judged on whether the ball goes in. Tell the boys that before you ask them to be brave with it.' },
      { title: 'What we take from him', lead: 'Four things we can use at K1 on Monday.',
        points: [
          'Be still on the ball on purpose. Stillness is information you are refusing to give them.',
          'Build to move them, not to keep it. Judge a build-up by whether they got dragged out, not by the pass count.',
          'Read the numbers before you choose short or long.',
          'Pay for it in fitness. If we press high and build short, we must be the fitter team.',
        ],
        quote: { text: 'I can’t burn talent. It is the coach’s responsibility not to squander it.', by: 'Roberto De Zerbi' },
        board: { morph: 'dezerbi_4222' },
        caption: 'Play the morph on the board: base · build trap · final third · counter-press.' },
      { title: 'Two lines for the coaching staff', lead: 'Not for the boys. For us.',
        points: [
          'He spends about eighty per cent of the training week on the attacking phase — and says that is exactly how he trains the defending, because he fixes the positions so the team is not caught unbalanced when the ball is lost. The two phases are one job.',
          'And he says tactics are no more than a quarter of his work. The rest is managing people.',
        ],
        quote: { text: 'If I explain something to one of my players, I have to explain it so well that it becomes almost impossible for him not to understand.', by: 'Roberto De Zerbi' },
        note: 'That last line is the standard to hold ourselves to on Workshop Fridays.' },
    ],
    sources: [
      'Wikipedia profile of Roberto De Zerbi (system description, Guardiola quote).',
      'Tottenham Hotspur official press-conference transcripts, August and September 2026.',
      'Sky Sports and ESPN match reports and analysis, August–September 2026.',
      'SoccerTutor, “De Zerbi’s tactics: bait the press” · Premier League analysis of the 3-2-5 build.',
      'Prompted in part by the “Build up direction” video, GEDFOOTBALL channel (not viewable here — concept covered from written coaching sources).',
    ],
  });
})(window.K1 = window.K1 || {});
